import React from 'react';
import { ArrowUpRight, BookOpen, CheckCircle2, ChevronRight, MessageCircle, Mic2, Target } from 'lucide-react';
import type { AppLanguage } from '../types';
import type { ProgressSummary } from '../utils/progressTracker';
import { CEFR_LEVELS, type CEFRLevel, getCEFRInfo } from '../utils/cefr';
import { getCEFRCurriculumFocus } from '../utils/curriculum';
import { getRoleplaysForLevel } from '../utils/roleplay';

interface Props { appLang: AppLanguage; cefrLevel: CEFRLevel; setCefrLevel: (level: CEFRLevel) => void; progress: ProgressSummary; onSpeak: (scenarioId?: string) => void; onPractice: () => void; }
const labels: Record<string,string> = { speaking:'Speaking', listening:'Listening', vocabulary:'Vocabulary', grammar:'Grammar', pronunciation:'Pronunciation', fluency:'Fluency' };

export const LearningDashboard: React.FC<Props> = ({ appLang, cefrLevel, setCefrLevel, progress, onSpeak, onPractice }) => {
  const so = appLang === 'so'; const info = getCEFRInfo(cefrLevel);
  const weakest = (Object.keys(progress.skills) as Array<keyof typeof progress.skills>).sort((a,b) => progress.skills[a].score - progress.skills[b].score)[0] ?? 'speaking';
  const focus = getCEFRCurriculumFocus(cefrLevel, weakest); const roleplays = getRoleplaysForLevel(cefrLevel).slice(0,3);
  return <div className="space-y-4 sm:space-y-5">
    <section className="overflow-hidden rounded-[1.75rem] border border-app-border bg-app-surface shadow-elevation-md">
      <div className="border-b border-app-border bg-primary px-5 py-6 text-white sm:px-7"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-white/70">{so ? 'Qorshaha maanta' : 'Today at a glance'}</p><h2 className="mt-2 max-w-md font-display text-2xl font-bold leading-tight sm:text-3xl">{so ? 'Tallaabo yar. Horumar muuqda.' : 'One focused session beats a scattered hour.'}</h2></div><Target className="mt-1 h-6 w-6 shrink-0 text-secondary" /></div><p className="mt-3 max-w-xl text-sm leading-6 text-white/75">{so ? 'Waxaad ku jirtaa waddada saxda ah.' : 'Your path is built from your level, your practice, and what needs attention next.'}</p></div>
      <div className="grid gap-px bg-app-border sm:grid-cols-3"><div className="bg-app-surface p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-text-muted">Level</p><p className="mt-1 text-lg font-bold">{info.level} · {info.title}</p></div><div className="bg-app-surface p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-text-muted">Focus</p><p className="mt-1 text-lg font-bold">{labels[weakest]}</p></div><div className="bg-app-surface p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-text-muted">Streak</p><p className="mt-1 text-lg font-bold">{progress.streakDays} {so ? 'maalin' : 'days'}</p></div></div>
    </section>
    <section className="grid gap-4 lg:grid-cols-[1.15fr_.85fr]">
      <div className="rounded-[1.75rem] border border-app-border bg-app-surface p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-primary">Next up</p><h3 className="mt-2 text-xl font-bold leading-tight">{focus.objective}</h3></div><span className="rounded-full bg-app-elevated px-2.5 py-1 text-xs font-bold text-text-muted">12 min</span></div><div className="mt-5 border-l-2 border-primary pl-4"><p className="text-sm font-semibold leading-6">{focus.task}</p><p className="mt-2 text-xs leading-5 text-text-secondary">{focus.successSignal}</p></div><div className="mt-6 flex flex-col gap-2 sm:flex-row"><button onClick={()=>onSpeak()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-bold text-white"><MessageCircle className="h-4 w-4" />{so ? 'Ku hadal hadda' : 'Speak now'}<ArrowUpRight className="h-4 w-4" /></button><button onClick={onPractice} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-app-border px-4 text-sm font-bold"><Mic2 className="h-4 w-4" />{so ? 'Ku celceli' : 'Practice sounds'}</button></div></div>
      <div className="rounded-[1.75rem] border border-app-border bg-app-surface p-5 sm:p-6"><div className="flex items-center gap-2"><BookOpen className="h-4 w-4 text-primary" /><h3 className="font-bold">{so ? 'Waxaad awooddaa' : 'Your can-do list'}</h3></div><div className="mt-5 space-y-3">{info.canDo.slice(0,3).map(item=><div key={item} className="flex gap-2 text-sm leading-5 text-text-secondary"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-success" />{item}</div>)}</div></div>
    </section>
    <section className="rounded-[1.75rem] border border-app-border bg-app-surface p-5 sm:p-6"><div className="flex items-end justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-primary">Choose your level</p><h3 className="mt-2 text-xl font-bold">{so ? 'Meesha aad joogto' : 'Set the right challenge'}</h3></div><span className="text-xs text-text-muted">CEFR</span></div><div className="mt-5 grid grid-cols-6 gap-1.5">{CEFR_LEVELS.map(item=><button key={item.level} onClick={()=>setCefrLevel(item.level)} className={`min-h-10 rounded-lg text-xs font-bold transition ${item.level===cefrLevel?'bg-primary text-white':'bg-app-elevated text-text-secondary hover:text-text-primary'}`}>{item.level}</button>)}</div></section>
    <section><div className="mb-3 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-primary">Real situations</p><h3 className="mt-1 text-xl font-bold">{so ? 'Wax aad ku isticmaali karto' : 'Practice for real life'}</h3></div><ChevronRight className="h-5 w-5 text-text-muted" /></div><div className="grid gap-3 md:grid-cols-3">{roleplays.map(role=><button key={role.id} onClick={()=>onSpeak(role.id)} className="group rounded-[1.5rem] border border-app-border bg-app-surface p-4 text-left transition hover:-translate-y-0.5 hover:border-primary/50"><div className="flex items-center justify-between"><span className="text-xs font-black uppercase tracking-wider text-primary">{role.titleEn.slice(0,2)}</span><ArrowUpRight className="h-4 w-4 text-text-muted group-hover:text-primary" /></div><p className="mt-8 text-sm font-bold">{so ? role.titleSo : role.titleEn}</p><p className="mt-1 text-xs leading-5 text-text-muted">{so ? role.goalSo : role.goalEn}</p></button>)}</div></section>
  </div>;
};
