import { LanguageInfo, TargetLanguageCode } from '../types';

export const SUPPORTED_LANGUAGES: Record<TargetLanguageCode, LanguageInfo> = {
  en: {
    code: 'en',
    name: 'English',
    nameSo: 'Ingiriisi',
    nativeName: 'English',
    flag: '🇬🇧',
    speechCode: 'en-US',
    welcomeMessage: 'Hello! I am Moke E. What would you like to speak about today?',
    welcomeMessageSo: 'Salaan! Waxaan ahay Moke E. Maxaad jeclaan lahayd inaad maanta ka hadasho?',
    samplePhrases: [
      {
        phrase: 'Where is the nearest subway station?',
        translationSo: 'Xaggee ku yaallaa xarunta tareenka dhulka hoostiisa ee ugu dhow?',
        translationEn: 'Where is the nearest subway station?',
        phonetic: '/wɛər ɪz ðə ˈnɪərɪst ˈsʌbweɪ ˈsteɪʃən/',
      },
      {
        phrase: 'It is a pleasure to meet you.',
        translationSo: 'Waa sharaf weyn inaan kula kulmo.',
        translationEn: 'It is a pleasure to meet you.',
        phonetic: '/ɪt ɪz ə ˈplɛʒər tuː miːt juː/',
      },
      {
        phrase: 'Could you please speak a little slower?',
        translationSo: 'Fadlan ma yara tartiibin kartaa hadalka?',
        translationEn: 'Could you please speak a little slower?',
        phonetic: '/kʊd juː pliːz spiːk ə ˈlɪtl ˈsloʊər/',
      },
      {
        phrase: 'I would like to order a warm cappuccino.',
        translationSo: 'Waxaan jeclaan lahaa inaan dalbado koob bun cappuccino ah oo kulul.',
        translationEn: 'I would like to order a warm cappuccino.',
        phonetic: '/aɪ wʊd laɪk tuː ˈɔːrdər ə wɔːrm ˌkæpʊˈtʃiːnoʊ/',
      },
    ],
  },
  ar: {
    code: 'ar',
    name: 'Arabic',
    nameSo: 'Carabi',
    nativeName: 'العربية',
    flag: '🇸🇦',
    speechCode: 'ar-SA',
    welcomeMessage: 'أهلاً وسهلاً! أنا موكي إي، رفيقك الذكي لتعلم اللغة العربية والنطق الصحيح.',
    welcomeMessageSo: 'Soo dhawow! Waxaan ahay Moke E, saaxiibkaaga barashada Carabiga iyo saxidda dhawaaqa.',
    samplePhrases: [
      {
        phrase: 'السلام عليكم ورحمة الله وبركاته',
        translationSo: 'Nabadgelyo, naxariis iyo barako Eebbe korkiinna ha ahaato.',
        translationEn: 'Peace, mercy and blessings of Allah be upon you.',
        phonetic: '/as-salaamu ʕalajkum wa raħmatul-laahi wa barakaatuh/',
      },
      {
        phrase: 'أود أن أطلب فنجاناً من القهوة من فضلك',
        translationSo: 'Waxaan jeclaan lahaa inaan dalbado koob qaxwo ah, fadlan.',
        translationEn: 'I would like to order a cup of coffee, please.',
        phonetic: '/ʔawaddu ʔan ʔatˤluba find͡ʒaanan mina l-qahwati min fadˤlik/',
      },
      {
        phrase: 'فرصة سعيدة جداً بلقائك اليوم',
        translationSo: 'Waa fursad aad u wanaagsan inaan maanta kula kulmo.',
        translationEn: 'Very pleased to meet you today.',
        phonetic: '/fursˤatun saʕiːdatun d͡ʒiddan bi-liqaːʔika l-jawm/',
      },
      {
        phrase: 'هل يمكنك مساعدتي في العثور على الفندق؟',
        translationSo: 'Ma iga caawin kartaa inaan helo hudheelka?',
        translationEn: 'Can you help me find the hotel?',
        phonetic: '/hal jumkinuka musaːʕadatiː fiː l-ʕuthuːri ʕalaː l-funduq/',
      },
    ],
  },
  so: {
    code: 'so',
    name: 'Somali',
    nameSo: 'Af-Soomaali',
    nativeName: 'Af Soomaali',
    flag: '🇸🇴',
    speechCode: 'so-SO',
    welcomeMessage: 'Kusoo dhawow Moke E! Aynu wada bilowno sheeko iyo ku hadalka afka Soomaaliga.',
    welcomeMessageSo: 'Kusoo dhawow Moke E! Aynu wada bilowno sheeko iyo ku hadalka afka Soomaaliga.',
    samplePhrases: [
      {
        phrase: 'Subax wanaagsan, sideed saaka ku waabariisatay?',
        translationSo: 'Subax wanaagsan, sideed saaka ku waabariisatay?',
        translationEn: 'Good morning, how did you wake up this morning?',
        phonetic: '/sʊbæħ wænɑːɡsæn siːdeːd sɑːkæ kʊ wɑːbæriːsætæj/',
      },
      {
        phrase: 'Waan ku faraxsanahay inaan kula kulmo maanta.',
        translationSo: 'Waan ku faraxsanahay inaan kula kulmo maanta.',
        translationEn: 'I am happy to meet you today.',
        phonetic: '/wɑːn kʊ færæxsænæhæj ɪnɑːn kʊlæ kʊlmɔ mɑːntæ/',
      },
      {
        phrase: 'Fadlan ma ii sheegi kartaa halka suuqu ku yaallo?',
        translationSo: 'Fadlan ma ii sheegi kartaa halka suuqu ku yaallo?',
        translationEn: 'Could you please tell me where the market is?',
        phonetic: '/fædlæn mæ iː ʃeːɡiː kærtɑː hælkæ suːqʊ kʊ jɑːllɔ/',
      },
    ],
  },
  fr: {
    code: 'fr',
    name: 'French',
    nameSo: 'Faransiis',
    nativeName: 'Français',
    flag: '🇫🇷',
    speechCode: 'fr-FR',
    welcomeMessage: 'Bonjour! Je suis Moke E. Améliorons votre français et votre prononciation!',
    welcomeMessageSo: 'Subax wanaagsan! Waxaan ahay Moke E. Aynu horumarinno Faransiiskaaga iyo dhawaaqaaga!',
    samplePhrases: [
      {
        phrase: 'Enchanté de faire votre connaissance.',
        translationSo: 'Sharaf bay ii tahay inaan ku barto.',
        translationEn: 'Delighted to make your acquaintance.',
        phonetic: '/ɑ̃.ʃɑ̃.te də fɛʁ vɔtʁ kɔ.nɛ.sɑ̃s/',
      },
      {
        phrase: "Pouvez-vous m'indiquer le chemin de la gare?",
        translationSo: 'Ma i tusi kartaa jidka loo maro xarunta tareenka?',
        translationEn: 'Can you show me the way to the train station?',
        phonetic: '/pu.ve vu mɛ̃.di.ke lə ʃ(ə).mɛ̃ də la ɡaʁ/',
      },
      {
        phrase: "Je voudrais un croissant et un café, s'il vous plaît.",
        translationSo: 'Waxaan rabaa rooti croissant ah iyo qaxwo, fadlan.',
        translationEn: 'I would like a croissant and a coffee, please.',
        phonetic: '/ʒə vu.dʁɛ œ̃ kʁwa.sɑ̃ e œ̃ ka.fe sil vu plɛ/',
      },
    ],
  },
  es: {
    code: 'es',
    name: 'Spanish',
    nameSo: 'Isbaanish',
    nativeName: 'Español',
    flag: '🇪🇸',
    speechCode: 'es-ES',
    welcomeMessage: '¡Hola! Soy Moke E. ¿De qué te gustaría hablar y practicar hoy?',
    welcomeMessageSo: 'Hola! Waxaan ahay Moke E. Maxaad jeclaan lahayd inaad maanta ku hadasho?',
    samplePhrases: [
      {
        phrase: 'Mucho gusto en conocerte.',
        translationSo: 'Farxad weyn bay ii tahay inaan ku barto.',
        translationEn: 'Nice to meet you.',
        phonetic: '/ˈmutʃo ˈɣusto en koneˈseɾte/',
      },
      {
        phrase: '¿Dónde está la estación de autobuses más cercana?',
        translationSo: 'Xaggee ku yaallaa boosteejada basaska ee ugu dhow?',
        translationEn: 'Where is the nearest bus station?',
        phonetic: '/ˈdonde esˈta la estaˈsjon de awtoˈβuses mas seɾˈkana/',
      },
      {
        phrase: 'La cuenta, por favor.',
        translationSo: 'Xisaabta lacagta, fadlan.',
        translationEn: 'The check / bill, please.',
        phonetic: '/la ˈkwenta poɾ faˈβoɾ/',
      },
    ],
  },
  de: {
    code: 'de',
    name: 'German',
    nameSo: 'Jarmal',
    nativeName: 'Deutsch',
    flag: '🇩🇪',
    speechCode: 'de-DE',
    welcomeMessage: 'Guten Tag! Ich bin Moke E. Lass uns zusammen Deutsch sprechen.',
    welcomeMessageSo: 'Maalin wanaagsan! Waxaan ahay Moke E. Aan wada hadalno af-Jarmal.',
    samplePhrases: [
      {
        phrase: 'Freut mich sehr, Sie kennenzulernen.',
        translationSo: 'Aad baan ugu faraxsanahay inaan ku barto.',
        translationEn: 'Pleased to meet you.',
        phonetic: '/fʁɔɪ̯t mɪç zeːɐ̯ ziː ˈkɛnəntsuˌlɛʁnən/',
      },
      {
        phrase: 'Entschuldigung, wie viel kostet das?',
        translationSo: 'Iga raalli ahow, immisa ayuu kan joogaa?',
        translationEn: 'Excuse me, how much does that cost?',
        phonetic: '/ʔɛntˈʃʊldɪɡʊŋ viː fiːl ˈkɔstət das/',
      },
      {
        phrase: 'Ich möchte mein Deutsch jeden Tag verbessern.',
        translationSo: 'Waxaan rabaa inaan afkayga Jarmalka maalin kasta horumariyo.',
        translationEn: 'I want to improve my German every day.',
        phonetic: '/ʔɪç ˈmœçtə maɪ̯n dɔɪ̯tʃ ˈjeːdn̩ taːk fɛɐ̯ˈbɛsɐn/',
      },
    ],
  },
  tr: {
    code: 'tr',
    name: 'Turkish',
    nameSo: 'Turki',
    nativeName: 'Türkçe',
    flag: '🇹🇷',
    speechCode: 'tr-TR',
    welcomeMessage: 'Merhaba! Ben Moke E. Türkçe konuşmaya ve telaffuzunu geliştirmeye hazır mısın?',
    welcomeMessageSo: 'Marhaban! Waxaan ahay Moke E. Diyaar ma u tahay inaad af-Turki ku hadasho?',
    samplePhrases: [
      {
        phrase: 'Tanıştığımıza çok memnun oldum.',
        translationSo: 'Aad baan ugu faraxsanahay inaan is baranno.',
        translationEn: 'Nice to meet you.',
        phonetic: '/tanɯʃtɯːɯmɯza tʃok memnun oldum/',
      },
      {
        phrase: 'Lütfen bana yardım edebilir misiniz?',
        translationSo: 'Fadlan ma i caawin kartaa?',
        translationEn: 'Could you please help me?',
        phonetic: '/lytfen bana jaɾdɯm edebiˈliɾ misiniz/',
      },
      {
        phrase: 'Gününüz nasıl geçiyor?',
        translationSo: 'Sidee maalintaadu kuugu socotaa?',
        translationEn: 'How is your day going?',
        phonetic: '/ɡynyˈnyz naˈsɯl ɡeˈtʃijoɾ/',
      },
    ],
  },
  it: {
    code: 'it',
    name: 'Italian',
    nameSo: 'Talyaani',
    nativeName: 'Italiano',
    flag: '🇮🇹',
    speechCode: 'it-IT',
    welcomeMessage: 'Ciao! Sono Moke E. Parliamo italiano e perfezioniamo la tua pronuncia!',
    welcomeMessageSo: 'Ciao! Waxaan ahay Moke E. Aan ku hadalno Talyaani oo aan saxno dhawaaqaaga!',
    samplePhrases: [
      {
        phrase: 'Piacere di conoscerti!',
        translationSo: 'Farxad bay ii tahay inaan ku barto!',
        translationEn: 'Nice to meet you!',
        phonetic: '/pjaˈtʃe.re di koˈnoʃ.ʃer.ti/',
      },
      {
        phrase: 'Un caffè espresso, per favore.',
        translationSo: 'Koob qaxwo espresso ah, fadlan.',
        translationEn: 'An espresso coffee, please.',
        phonetic: '/uŋ kafˈfɛ eˈsprɛs.so per faˈvo.re/',
      },
      {
        phrase: 'Che bella giornata oggi!',
        translationSo: 'Waa maalin aad u qurux badan maanta!',
        translationEn: 'What a beautiful day today!',
        phonetic: '/ke ˈbɛl.la dʒorˈna.ta ˈɔd.dʒi/',
      },
    ],
  },
  zh: {
    code: 'zh',
    name: 'Chinese (Mandarin)',
    nameSo: 'Shiineys (Mandarin)',
    nativeName: '中文 (普通话)',
    flag: '🇨🇳',
    speechCode: 'zh-CN',
    welcomeMessage: '你好！我是 Moke E，很高兴陪你练习中文口语和发音！',
    welcomeMessageSo: 'Ni hao! Waxaan ahay Moke E, aad baan ugu faraxsanahay inaan ku baro Shiineyska!',
    samplePhrases: [
      {
        phrase: '你好，很高兴认识你。',
        translationSo: 'Nabad, aad baan ugu faraxsanahay inaan ku barto.',
        translationEn: 'Hello, very glad to meet you.',
        phonetic: '/nǐ hǎo, hěn gāo xìng rèn shi nǐ/',
      },
      {
        phrase: '请问洗手间在哪里？',
        translationSo: 'Fadlan musqusha/suuliga meeye?',
        translationEn: 'Excuse me, where is the restroom?',
        phonetic: '/qǐng wèn xǐ shǒu jiān zài nǎ lǐ/',
      },
      {
        phrase: '这个多少钱？',
        translationSo: 'Kan immisa weeye?',
        translationEn: 'How much is this?',
        phonetic: '/zhè ge duō shao qián/',
      },
    ],
  },
  ja: {
    code: 'ja',
    name: 'Japanese',
    nameSo: 'Jabaaniis',
    nativeName: '日本語',
    flag: '🇯🇵',
    speechCode: 'ja-JP',
    welcomeMessage: 'こんにちは！Moke Eです。一緒に日本語の会話と発音を練習しましょう！',
    welcomeMessageSo: 'Konnichiwa! Waxaan ahay Moke E. Aan wada baranno af-Jabaaniiska!',
    samplePhrases: [
      {
        phrase: '初めまして、よろしくお願いします。',
        translationSo: 'Waa kulankeenii ugu horreeyay, aad baan ugu faraxsanahay.',
        translationEn: 'Nice to meet you, please treat me well.',
        phonetic: '/ha.d͡ʑi.me.maɕi̥.te jo.ɾo.ɕi.kɯ o.ne.ɡa.i.ɕi.ma.sɯ/',
      },
      {
        phrase: '駅はどちらですか？',
        translationSo: 'Xaggee ku taal xarunta tareenka?',
        translationEn: 'Which way is the station?',
        phonetic: '/e.ki wa do.t͡ɕi.ɾa de.sɯ ka/',
      },
      {
        phrase: 'ありがとうございます。',
        translationSo: 'Aad baad u mahadsantahay.',
        translationEn: 'Thank you very much.',
        phonetic: '/a.ɾi.ɡa.toː ɡo.za.i.ma.sɯ/',
      },
    ],
  },
  sw: {
    code: 'sw',
    name: 'Swahili',
    nameSo: 'Sawaaxili',
    nativeName: 'Kiswahili',
    flag: '🇰🇪',
    speechCode: 'sw-KE',
    welcomeMessage: 'Hujambo! Mimi ni Moke E. Hebu tufanye mazungumzo na kuboresha matamshi yako!',
    welcomeMessageSo: 'Hujambo! Waxaan ahay Moke E. Aan baranno af-Sawaaxiliga!',
    samplePhrases: [
      {
        phrase: 'Habari za asubuhi? Nimefurahi kukutana nawe.',
        translationSo: 'Waran saaka? Waan ku faraxsanahay inaan kula kulmo.',
        translationEn: 'Good morning! I am happy to meet you.',
        phonetic: '/haˈba.ɾi za a.suˈbu.hi ni.me.fuˈɾa.hi ku.kuˈta.na na.we/',
      },
      {
        phrase: 'Tafadhali nisaidie kupata kituo cha basi.',
        translationSo: 'Fadlan iga caawi inaan helo xarunta baska.',
        translationEn: 'Please help me find the bus station.',
        phonetic: '/ta.faˈða.li ni.sa.iˈdi.e kuˈpa.ta kiˈtu.o tʃa ˈba.si/',
      },
      {
        phrase: 'Asante sana, siku njema!',
        translationSo: 'Aad baad u mahadsantahay, maalin wanaagsan!',
        translationEn: 'Thank you very much, have a nice day!',
        phonetic: '/aˈsan.te ˈsa.na ˈsi.ku ˈnd͡ʒe.ma/',
      },
    ],
  },
  ko: {
    code: 'ko',
    name: 'Korean',
    nameSo: 'Kuriyaan',
    nativeName: '한국어',
    flag: '🇰🇷',
    speechCode: 'ko-KR',
    welcomeMessage: '안녕하세요! 저는 Moke E입니다. 함께 즐겁게 대화하고 발음을 연습해요!',
    welcomeMessageSo: 'Annyeonghaseyo! Waxaan ahay Moke E. Aan ku hadalno Kuuriyaan!',
    samplePhrases: [
      {
        phrase: '만나서 반갑습니다. 좋은 하루 되세요.',
        translationSo: 'Farxad bay ii tahay inaan kula kulmo. Maalin wanaagsan.',
        translationEn: 'Nice to meet you. Have a nice day.',
        phonetic: '/man.na.sʌ pan.ɡap.sɯm.ni.da t͡ɕo.ɯn ha.ɾu twe.se.jo/',
      },
      {
        phrase: '이것 얼마예요?',
        translationSo: 'Kan immisa weeye?',
        translationEn: 'How much is this?',
        phonetic: '/i.ɡʌt ʌl.ma.je.jo/',
      },
      {
        phrase: '한국어 말하기 연습을 하고 싶어요.',
        translationSo: 'Waxaan rabaa inaan ku tababarto ku hadalka Kuuriyaanka.',
        translationEn: 'I want to practice speaking Korean.',
        phonetic: '/han.ɡu.ɡʌ mal.ha.ɡi jʌn.sɯ.bɯl ha.ɡo ɕi.pʰʌ.jo/',
      },
    ],
  },
};

export const CONVERSATION_SCENARIOS = [
  {
    id: 'general',
    titleSo: 'Sheeko Caadi ah & Saaxiibo',
    titleEn: 'Casual Chit-chat & Friends',
    icon: '💬',
    descriptionSo: 'Sheeko maalinle ah oo ku saabsan nolosha, cimilada, iyo hiwaayadaha.',
    descriptionEn: 'Daily casual talks about life, weather, interests, and hobbies.',
  },
  {
    id: 'travel',
    titleSo: 'Garoonka & Socdaalka',
    titleEn: 'Airport, Hotel & Travel',
    icon: '✈️',
    descriptionSo: 'Baasaboorka, tigidhada, hubinta boorsooyinka, iyo weydiinta jidka.',
    descriptionEn: 'Passports, boarding passes, asking directions, check-in.',
  },
  {
    id: 'coffee',
    titleSo: 'Maqaayadda & Dalbashada',
    titleEn: 'Coffee Shop & Restaurant',
    icon: '☕',
    descriptionSo: 'Dalbashada cuntada, cabitaanka, weydiinta qiimaha iyo bixinta biilka.',
    descriptionEn: 'Ordering meals, drinks, dietary choices, and settling the bill.',
  },
  {
    id: 'interview',
    titleSo: 'Waraysiga Shaqada',
    titleEn: 'Job Interview & Career',
    icon: '💼',
    descriptionSo: 'Ka jawaabista su’aalaha waraysiga, sharaxaadda waaya-aragnimadaada.',
    descriptionEn: 'Professional questions, skills, work experience, career goals.',
  },
  {
    id: 'doctor',
    titleSo: 'Dhaqtarka & Caafimaadka',
    titleEn: 'Doctor & Pharmacy',
    icon: '🏥',
    descriptionSo: 'Sharaxaadda xanuunka, dawooyinka, iyo talooyinka caafimaad.',
    descriptionEn: 'Describing symptoms, buying medications, healthcare advice.',
  },
  {
    id: 'shopping',
    titleSo: 'Suuqa & Iibsashada',
    titleEn: 'Shopping & Bargaining',
    icon: '🛍️',
    descriptionSo: 'Raadinta cabbirka saxda ah, gorgortanka qiimaha, iyo lacag bixinta.',
    descriptionEn: 'Checking sizes, asking for discounts, payment methods.',
  },
];
